name: Deploy to server

on: push # event
# a workflow needs multiple jobs to be able to execute.

jobs:
  first_job:
    runs-on: ubuntu-latest # operating system

    steps: 
      - name: Valentina

        run: echo "Hello to github actions world!"

  second_job:
    # needs is a keyword used to indicate that a job depends on another. It shouldn't execute until the other one sucessfully finishes.
    needs: first_job # links the first job to the second one. 
    runs-on: ubuntu-latest # operating system

    steps: 
      - name: Tests

        run: echo "Hello to my second job"